### ISSUE TITLE
Dynamic Modal using Vue.js

### ISSUE THREAD

**Issue by Muayyan** [doximity/vue-genome#41]
How to open a specific modal from the array of modal boxes?

**Comment by Muayyan** [comment]
``

**Comment by Austio** [comment]
@Muayyan Thanks so much for taking interest in the project and submitting an issue.  I created a quick PR that demonstrates the usage of the modal in an array like context.  That should be merged in soonish but here is the link.  In essence, the modal visibility is a simple prop and it emits a closedModal event you can use to switch off the modal.  

https://github.com/doximity/vue-genome/pull/44

That being said, we are currently in pretty active development on this library and I expect quite a changes over the next several weeks, so please feel free to use and participate but wouldn't use it in a production app for at least until we publish it up to npm, document and get a release tag on it.

**Comment by Austio** [comment]
Merged https://github.com/doximity/vue-genome/pull/44
